### ISSUE TITLE
Error when saving page

### ISSUE THREAD

**Issue by rdunk** [kixe/FieldtypeColor#1]
I'm seeing the following error when trying to save a page using this field with the Spectrum color picker:

`An invalid form control with name='colourpicker' is not focusable.`

**Comment by kixe** [comment]
@rdunk
Need some more information:
Browser?
Fieldsettings?
Saving with or without setting a value?
Field set required?

**Comment by kixe** [comment]
Cannot reproduce. Further information not provided. Closed.

**Comment by rdunk** [comment]
Sorry for the delay, ended up uninstalling for now. Will reopen if/when I have chance to check this again.

**Comment by kixe** [comment]
There exists a bug in chrome which may be related and cannot be solved from the modules side. Please provide informations about your setting to get the aibility reproducing the issue.

**Comment by nurkka** [comment]
Thanks for the module! I ran into a similar issue. The javascript console in chrome browser said "An invalid form control with name='defaultValue' is not focusable.". Therefore no page can be saved anymore, even the field settings. 
My settings were: Output as HEX-Color like #FFFFFF, Input as Colorpicker with custom options. My custom options were taken from http://bgrins.github.io/spectrum/, but I think the option that caused the issue was preferredFormat: "hex".
I was able to save the settings again, when live-editing the html in webdev tools. I just deleted the pattern-attribute from the input field "defaultValue". After that, the save-button worked again.
Hope this helps to identify the issue ...

**Comment by kixe** [comment]
**Replace this line** https://github.com/kixe/FieldtypeColor/blob/b4ef32e5b5acdcaadae74412ea6cf346787c16e8/InputfieldColor.module#L200
**with** `$this->removeAttr('pattern');`

Does it fix the issue?

**Comment by nurkka** [comment]
Yes, thank you, that fixed the issue!

**Comment by kixe** [comment]
Chrome browser throws error if an inputfield which asks for validation (pattern attribute) is hidden or invisible (CSS) and therefore not focusable, which is the case if spectrum color picker is used. The update will remove the pattern attribute in this case.

fixed.
